---
namespace: cloud
name: aws_troubleshooting
version: 5.0.0-dev0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: Amazon AWS roles and playbooks for Ansible.
license_file: COPYING
tags:
  - amazon
  - aws
  - cloud
  - infrastructure
  - cluster
dependencies:
  amazon.aws: '>=10.0.0'
  community.aws: '>=10.0.0'
repository: https://github.com/redhat-cop/cloud.aws_troubleshooting
documentation: ''
homepage: https://github.com/redhat-cop/cloud.aws_troubleshooting
issues: https://github.com/redhat-cop/cloud.aws_troubleshooting/issues
build_ignore:
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
  - 'changelogs/.plugin-cache.yaml'
