---
name: Linters

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - stable-*

jobs:
  tox-linters:
    uses: ansible-network/github_actions/.github/workflows/tox-linters.yml@main
